export const SET_USER_ACCOUNT = 'SET_USER_ACCOUNT';
export const SET_USER_BALANCE = 'SET_USER_BALANCE';
export const SET_USER_TRANSACTIONS = 'SET_USER_TRANSACTIONS';
export const SET_USER_POSITIONS = 'SET_USER_POSITIONS';
export const SET_USER_ORDERS = 'SET_USER_ORDERS';
export const SET_USER_ORDER_LABELS = 'SET_USER_ORDER_LABELS';
export const SET_USER_TOKENS = 'SET_USER_TOKENS';

export const SET_CONTRACT_DETAILS = 'SET_CONTRACT_DETAILS';
export const SET_ORDERBOOK = 'SET_ORDERBOOK';
export const SET_RECENT_TRADES = 'SET_RECENT_TRADES';
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS';
export const SET_SELECTED_TOKEN = 'SET_SELECTED_TOKEN';
export const CLEAR_SELECTED_TOKEN = 'CLEAR_SELECTED_TOKEN';
export const SET_CURRENT = 'SET_CURRENT';

export const SET_IS_CONNECTED = 'SET_IS_CONNECTED';
export const TX_PROCESSING = 'TEX_PROCESSING';
export const SET_TX_RECEIPT = 'SET_TX_RECEIPT';
export const RESET_TX_STATE = 'RESET_TX_STATE';
export const SET_PROCESSING_ERROR = 'SET_PROCESSING_ERROR';
export const CLEAR_PROCESSING_ERROR = 'CLEAR_PROCESSING_ERROR';
